package pl.sq3tom.logger;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.location.Location;import android.location.LocationListener;import android.location.LocationManager;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 LinearLayout terrain,history,acts,satBox; EditText call,dt,freq,rstS,rstR,power,grid,comment,satRx,satTx,actRef,actQth; TextView status,person,gpsInfo,actInfo; Spinner band,mode,satellite,satType; String activation=""; ArrayList<String> qsos=new ArrayList<>(); android.content.SharedPreferences pref;
 String[] bands={"2m","70cm","10m","12m","15m","17m","20m","30m","40m","80m","160m"}; String[] modes={"AM","SSB","DMR","FM","C4FM","FT8","FT4","JS8","CW"};
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);pref=getSharedPreferences("logger",0);bind();setup();}
 void bind(){terrain=findViewById(R.id.terrain);history=findViewById(R.id.history);acts=findViewById(R.id.activations);satBox=findViewById(R.id.satBox);call=findViewById(R.id.call);dt=findViewById(R.id.datetime);freq=findViewById(R.id.freq);rstS=findViewById(R.id.rstSent);rstR=findViewById(R.id.rstRcvd);power=findViewById(R.id.power);grid=findViewById(R.id.grid);comment=findViewById(R.id.comment);satRx=findViewById(R.id.satRx);satTx=findViewById(R.id.satTx);actRef=findViewById(R.id.actRef);actQth=findViewById(R.id.actQth);status=findViewById(R.id.status);person=findViewById(R.id.person);gpsInfo=findViewById(R.id.gpsInfo);actInfo=findViewById(R.id.actInfo);band=findViewById(R.id.band);mode=findViewById(R.id.mode);satellite=findViewById(R.id.satellite);satType=findViewById(R.id.satType);}
 void setup(){band.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,bands));mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,modes));satellite.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"ISS","SO-50","AO-91","AO-92","PO-101","RS-44","Inny"}));satType.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"FM SPLIT","SSB SPLIT","APRS","Packet"}));dt.setText(utc());load();
  findViewById(R.id.tabTerrain).setOnClickListener(v->show(terrain));findViewById(R.id.tabHistory).setOnClickListener(v->{renderHistory();show(history);});findViewById(R.id.tabAct).setOnClickListener(v->show(acts));findViewById(R.id.save).setOnClickListener(v->saveQso());findViewById(R.id.newQso).setOnClickListener(v->clear());findViewById(R.id.gps).setOnClickListener(v->gps());findViewById(R.id.sat).setOnClickListener(v->satBox.setVisibility(satBox.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));findViewById(R.id.lookup).setOnClickListener(v->lookup());
  View.OnClickListener al=v->{activation=((Button)v).getText().toString().replaceAll("[^A-Z]","");actInfo.setText("Wybrano: "+activation);};findViewById(R.id.pota).setOnClickListener(al);findViewById(R.id.sota).setOnClickListener(al);findViewById(R.id.llota).setOnClickListener(al);findViewById(R.id.wwff).setOnClickListener(al);findViewById(R.id.saveAct).setOnClickListener(v->{pref.edit().putString("act",activation).apply();actInfo.setText("Aktywna: "+activation+" "+actRef.getText()+" "+actQth.getText());});
  satellite.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){} public void onItemSelected(AdapterView<?> p,View v,int pos,long id){presetSat((String)p.getItemAtPosition(pos));}});
 }
 void show(View v){terrain.setVisibility(v==terrain?View.VISIBLE:View.GONE);history.setVisibility(v==history?View.VISIBLE:View.GONE);acts.setVisibility(v==acts?View.VISIBLE:View.GONE);}
 String utc(){return new SimpleDateFormat("yyyy-MM-dd HH:mm 'UTC'",Locale.US){{setTimeZone(TimeZone.getTimeZone("UTC"));}}.format(new Date());}
 void saveQso(){String c=call.getText().toString().trim().toUpperCase();if(c.isEmpty()){toast("Wpisz znak");return;}String q=c+" | "+utc()+" | "+band.getSelectedItem()+" | "+mode.getSelectedItem()+" | "+freq.getText()+" MHz | RST "+rstS.getText()+"/"+rstR.getText()+" | "+power.getText()+" W"+(activation.isEmpty()?"":" | "+activation+" "+actRef.getText());qsos.add(q);pref.edit().putStringSet("qsos",new HashSet<>(qsos)).putString("band",band.getSelectedItem().toString()).putString("mode",mode.getSelectedItem().toString()).putString("freq",freq.getText().toString()).putString("power",power.getText().toString()).apply();status.setText("● zapisano: "+c);toast("QSO zapisane");clear();}
 void clear(){call.setText("");comment.setText("");rstS.setText("59");rstR.setText("59");dt.setText(utc());status.setText("● gotowy");}
 void renderHistory(){history.removeAllViews();for(String q:qsos){Button b=new Button(this);b.setText(q);b.setTextColor(Color.WHITE);b.setOnClickListener(v->{call.setText(q.split(" \\|")[0]);show(terrain);toast("QSO wybrane do edycji");});history.addView(b);}}
 void load(){qsos.addAll(pref.getStringSet("qsos",new HashSet<>()));freq.setText(pref.getString("freq",""));power.setText(pref.getString("power","5"));activation=pref.getString("act","");actInfo.setText(activation.isEmpty()?"Brak aktywnej aktywacji.":"Aktywna: "+activation);}
 void lookup(){String c=call.getText().toString().trim().toUpperCase();if(c.isEmpty())return;person.setText(c+"\nWyszukiwanie QRZ zostanie podłączone przez API w następnym etapie.");person.setVisibility(View.VISIBLE);}
 void presetSat(String s){String rx="",tx="";if(s.equals("ISS")){rx="145.800";tx="145.200";}else if(s.equals("SO-50")){rx="436.800";tx="145.850";}else if(s.equals("AO-91")){rx="145.960";tx="435.250";}else if(s.equals("AO-92")){rx="145.880";tx="437.350";}else if(s.equals("PO-101")){rx="437.500";tx="145.900";}else if(s.equals("RS-44")){rx="145.965";tx="145.935";}satRx.setText(rx);satTx.setText(tx);}
 void gps(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION},9);return;}LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);try{Location l=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l==null)l=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(l!=null){grid.setText(locator(l.getLatitude(),l.getLongitude()));gpsInfo.setText("📍 "+l.getLatitude()+", "+l.getLongitude()+" · "+grid.getText());}else toast("Brak pozycji GPS — spróbuj ponownie");}catch(Exception e){toast("GPS niedostępny");}}
 String locator(double lat,double lon){String L="ABCDEFGHIJKLMNOPQRSTUVWXYZ";lon+=180;lat+=90;int a=(int)(lon/20),b=(int)(lat/10),c=(int)((lon%20)/2),d=(int)(lat%10);int e=(int)(((lon%2)*12));int f=(int)(((lat%10)%2)*24);return ""+L.charAt(a)+L.charAt(b)+c+d+L.charAt(e)+L.charAt(f);}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
